version: "3.2"
services:
  air-quality-ui:
    build: ./UI/
    ports:
      - 6061:80
    depends_on:
      - air-quality-db
    links:
      - air-quality-db
    volumes:
    - ./UI/app:/UI:ro

  air-quality-parser:
    build: ./parser/
    depends_on:
      - air-quality-db
    links:
      - air-quality-db

  air-quality-event-api:
    build: ./event-api/
    ports:
      - 6060:5000
    depends_on:
      - air-quality-db
    links:
      - air-quality-db
  
  air-quality-db:
    build: ./database/
    environment:
      - MYSQL_ROOT_PASSWORD=T2sF8fxIK7ctLS0kR1gT
