version: "3.2"
services:
  air-quality-ui:
    build: ./UI/
    ports:
      - 80:80
    depends_on:
      - air-quality-db
    links:
      - air-quality-db

  air-quality-parser:
    build: ./parser/
    depends_on:
      - air-quality-db
    links:
      - air-quality-db
  
  air-quality-db:
    build: ./database/
    environment:
      - MYSQL_ROOT_PASSWORD=d04kdzepq33kadf3qp314rm3o
      - MYSQL_INITDB_SKIP_TZINFO=1
    ports:
      - 3306:3306
#    volumes:
#    - ./storage/db:/var/lib/mysql:rw
