-- MySQL Script generated by MySQL Workbench
-- mar. 10 mars 2020 14:00:58 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`driver`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`driver` (
  `id_driver` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  PRIMARY KEY (`id_driver`),
  UNIQUE INDEX `id_driver_UNIQUE` (`id_driver` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sensor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sensor` (
  `id_sensor` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `driver_id_driver` INT NOT NULL,
  PRIMARY KEY (`id_sensor`),
  UNIQUE INDEX `id_sensor_UNIQUE` (`id_sensor` ASC) VISIBLE,
  INDEX `fk_sensor_driver1_idx` (`driver_id_driver` ASC) VISIBLE,
  CONSTRAINT `fk_sensor_driver1`
    FOREIGN KEY (`driver_id_driver`)
    REFERENCES `mydb`.`driver` (`id_driver`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`values`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`values` (
  `timestamp` INT NULL,
  `unit` VARCHAR(255) NULL,
  `value` VARCHAR(255) NULL,
  `id_value` INT NOT NULL AUTO_INCREMENT,
  `sensor_id_sensor` INT NOT NULL,
  PRIMARY KEY (`id_value`),
  INDEX `fk_values_sensor1_idx` (`sensor_id_sensor` ASC) VISIBLE,
  UNIQUE INDEX `id_value_UNIQUE` (`id_value` ASC) VISIBLE,
  CONSTRAINT `fk_values_sensor1`
    FOREIGN KEY (`sensor_id_sensor`)
    REFERENCES `mydb`.`sensor` (`id_sensor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
